# -*- coding: utf-8 -*-
"""BBN

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PHdmEz8DnasmWcapHZrNGRMROIKrKHVs
"""

!pip install pgmpy

from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination
import pandas as pd
import networkx as nx

data = pd.read_csv("BayesianNetwork.csv")

model = BayesianModel([('age','target'),('sex','target'), ('trestbps', 'target'),])

nx.draw(model, with_labels = True)

model.fit(data, estimator = MaximumLikelihoodEstimator)

infer = VariableElimination(model)

q = infer.query(variables = ['target'], evidence= {
    "age": 30,
    "sex":0
})
print(q)