# -*- coding: utf-8 -*-
"""Candidate Elimination

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fSdZDhm0GmVCh10ijK9t4h4Z5FrMcQmy
"""

import pandas as pd
import numpy as np

data = pd.read_csv("Candidate_Elimination.csv")
X = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

s = ['0' for i in range(len(X[0]))]
g = [['?' for i in range(len(X[0]))] for i in range(len(X[0]))]

for i,h in enumerate(X):
  if y[i]=="yes":
    s = h.copy()
    break

for i,h in enumerate(X):
  if y[i]=="yes":
    for j in range(len(s)):
      if h[j]!=s[j]:
        s[j]="?"
        g[j][j]="?"
  elif y[i]=="no":
    for j in range(len(s)):
      if h[j]!=s[j]:
        g[j][j] = s[j]
      else:
        g[j][j] = "?"

temp = ["?" for x in range(len(X[0]))]
general_h = []
for i in g:
  if i!=temp:
    general_h.append(i)

specific_h = s.copy()

print("The most specific hypothesis is: ",specific_h)
print("The most general hypothesis is: ",general_h)