# -*- coding: utf-8 -*-
"""Naive_Bayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Tx5DQbDUokM0yBB9gwZHe0GecsN-OHq
"""

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder

data = load_iris()
X = data.data
y = data.target

le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])
X[:,1] = le.fit_transform(X[:,1])
X[:,2] = le.fit_transform(X[:,2])
X[:,3] = le.fit_transform(X[:,3])

x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)

model = GaussianNB()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print("The accuracy score of Naive Bayes Classifier is: ", format(accuracy_score(y_test,y_pred),"0.3f"))